### ISSUE TITLE
SSH agent forwarding to WSL2

### ISSUE THREAD

**Issue by Sourabh-ALTEN** [rupor-github/wsl-ssh-agent#44] opened 2023-07-13 19:22 UTC
Hello @rupor-github ,

I am partially able to use the OpenSSH key (created in Windows) inside my WSL2 (Ubuntu 22.04). I have below setup:

1. Using Windows 11 (OS build 22621.1702) with OpenSSH enabled and running without any issues and WSL2 with Ubuntu 22.04
2. In WSL2 copied the `wsl-ssh-agent-relay` file to `${HOME}/.local/bin/` and added below lines to `~/.bashrc` as mentioned in the [README ](https://github.com/rupor-github/wsl-ssh-agent#wsl2-compatibility)
```
${HOME}/.local/bin/wsl-ssh-agent-relay start
export SSH_AUTH_SOCK=${HOME}/.ssh/wsl-ssh-agent.sock
```
3. Also copied `npiperelay.exe` from [wsl-ssh-agent.zip](https://github.com/rupor-github/wsl-ssh-agent/releases/download/v1.6.6/wsl-ssh-agent.zip) to `/mnt/c/Users/<USER>`
4. Shutdown WSL2 and restarted it. And tried to clone to Git repo (key is already added to Git). But this didn't work. I don't have `wsl-ssh-agent.sock` file in `${HOME}/.ssh/` but only `agent.sock`.
5. `ssh-add -L` didn't return any keys and complained `Error connecting to agent: No such file or directory`. I don't know why above solution didn't work for me (please let me know if I have missed any steps)

I came across issue [Error connecting to agent: No such file or directory](https://github.com/rupor-github/wsl-ssh-agent/issues/34) and edited `~/.bashrc` to include
```
export SSH_AUTH_SOCK=$HOME/.ssh/agent.sock
ss -a | grep -q $SSH_AUTH_SOCK
if [ $? -ne 0   ]; then
    rm -f $SSH_AUTH_SOCK
    ( setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"/mnt/c/test/npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork & ) >/dev/null 2>&1
fi
```
And restarted the WSL2. Now, the keys are loaded by `ssh-add - L`. I have similar results in WSL2 and Powershell. Also, cloning from Git works fine.
But when I try to `ssh` to a server (key is added to `~/.ssh/authorized_keys`) I get error `ssh: Could not resolve hostname example.com: Name or service not known`
This works fine from Powershell.
I checked the DNS in WSL2 and it seems fine. `nslookup` could return the IP address.

Could you please let me know what could be the issue and how can I resolve it?

P.S: Please let me know if any info is missing here

Thanks in advance

**Comment by rupor-github** [comment] 2023-07-13 19:52
I am really sorry - you got me all confused... What problem we are trying to solve here? DNS not resolving host name "example.com" in WSL2? Or something else? Why did you have to add lines into your .bashrc instead of following solution suggested in the issue you are linking to?  Did you try to use ping to see if ssh has anything to do with your troubles? I am not technical support - could only answer very concrete question I could understand and/or reproduce...

**Comment by Sourabh-ALTEN** [comment] 2023-07-14 06:37
Hi @rupor-github thanks for quick reply. Sorry if my description was misleading. It's not the issue with DNS. `ping` is working fine. 

> Why did you have to add lines into your .bashrc instead of following solution suggested in the issue you are linking to?

First I followed your solution as given in [WSL2 compatibility](https://github.com/rupor-github/wsl-ssh-agent#wsl2-compatibility) but this didn't work for me. Then I added the lines as mentioned in the linked issue above (workaround). Now `ssh-add -L` is working. I hope I am clear now. But still `ssh` to my server is failing with message `ssh: Could not resolve hostname example.com: Name or service not known` whereas cloning to Git repo with same keys is working. Below is the output of `ssh -vvv example.com`
```
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'
debug2: resolving "example.com" port 22
debug3: resolve_host: lookup example.com:22
ssh: Could not resolve hostname example.com: Name or service not known
```
I am not completely sure if this issue is related to `wsl-ssh-agnet` or `npiperelay.exe`.
Please let me know your inputs

**Comment by rupor-github** [comment] 2023-07-14 12:21
Could you please try `sudo ping example.com` and share the result? Judging by the error message it has nothing to do with `ssh`. This is what I see on my box:
![image](https://github.com/rupor-github/wsl-ssh-agent/assets/5368784/0709a19e-1f21-4e92-8ab0-78eceaac7ca4)

You are running as a root user if I am not mistaken - not as regular one. Are you sure your installation of Ubuntu on the WSL2 was successful and this is intended?

**Comment by rupor-github** [comment] 2023-07-17 13:04
@Sourabh-ALTEN any news?

**Comment by Sourabh-ALTEN** [comment] 2023-07-18 08:18
Hi @rupor-github , sorry for delayed response.

`sudo ping example.com` is working
```
PING example.com (93.184.216.34) 56(84) bytes of data.
64 bytes from 93.184.216.34 (93.184.216.34): icmp_seq=1 ttl=49 time=112 ms
64 bytes from 93.184.216.34 (93.184.216.34): icmp_seq=2 ttl=49 time=111 ms
```
And `ssh -vvv example.com` results in
```
OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'
debug2: resolving "example.com" port 22
debug3: resolve_host: lookup example.com:22
debug3: ssh_connect_direct: entering
debug1: Connecting to example.com [93.184.216.34] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x10
```

**Comment by rupor-github** [comment] 2023-07-18 18:52
It looks to me like it is working now, then? Host is resolved properly (it was not resolving before).

**Closed as completed** 2023-07-28 20:08 UTC
Labels: question, wontfix
